environment:
  RUST: stable
  VCPKG_PANIC: 1
  matrix:
    - TARGET: x86_64-pc-windows-msvc
      RUSTFLAGS: -Ctarget-feature=+crt-static
      RUST: nightly
      VCPKG_DEFAULT_TRIPLET: x64-windows-static
    - TARGET: x86_64-pc-windows-msvc
      VCPKG_DEFAULT_TRIPLET: x64-windows
      VCPKGRS_DYNAMIC: 1
    - TARGET: i686-pc-windows-msvc
      RUSTFLAGS: -Ctarget-feature=+crt-static
      RUST: nightly
      VCPKG_DEFAULT_TRIPLET: x86-windows-static
    - TARGET: i686-pc-windows-msvc
      VCPKG_DEFAULT_TRIPLET: x86-windows
      VCPKGRS_DYNAMIC: 1
    
install:
  # Install Rust
  - curl -sSf -o rustup-init.exe https://win.rustup.rs/
  - rustup-init.exe -y --default-host %TARGET% --default-toolchain %RUST%
  - set PATH=%PATH%;C:\Users\appveyor\.cargo\bin
  - rustc -V
  - cargo -V
  - git clone https://github.com/Microsoft/vcpkg c:\projects\vcpkg
  - git --git-dir=vcpkg\.git log -1 --format=oneline
  - c:\projects\vcpkg\bootstrap-vcpkg.bat
  - set VCPKG_ROOT=c:\projects\vcpkg
  - echo yes > %VCPKG_ROOT%\Downloads\AlwaysAllowDownloads
  - if defined VCPKG_ROOT %VCPKG_ROOT%\vcpkg.exe install sqlite3 libpq libmysql curl zeromq 

build: false

test_script:
  # why?
  - if defined VCPKG_DEFAULT_TRIPLET set VCPKG_ROOT=c:\projects\vcpkg
  - rustc --version
  - cargo --version
  - set RUST_BACKTRACE=1
  - set RUST_TEST_THREADS=1
  - cargo update
  - cargo build --all
  - cargo test --all
  - cargo run --manifest-path vcpkg_cli\Cargo.toml -- probe sqlite3
  - cargo run --manifest-path systest\Cargo.toml 
